PSPSDK=$(shell psp-config --pspsdk-path)

TARGET_LIB = ../lib/libaa.a
OBJS = aafont.o \
       aafonts.o \
       aavyhen.o \
       aamktabl.o \
       aamem.o \
       aaprintf.o \
       aahelp.o \
       aaslnkbd.o \
       aaslang.o \
       aafastre.o \
       fontgl.o \
       font16.o \
       font14.o \
       fontx16.o \
       fontx13.o \
       fontx13b.o \
       fontcour.o \
       aarec.o \
       font9.o \
       font8.o \
       fontline.o \
       aalib.o \
       aaflush.o \
       aarender.o \
       aaout.o \
       aain.o \
       aaedit.o \
       aaregist.o \
       aasave.o \
       aastdout.o \
       aagu.o \
       aastdin.o \
       scr_printf.o \
       aaparse.o

INCDIR = ../include
CFLAGS = -G0 -g -O2

include $(PSPSDK)/lib/build.mak
