   .set noreorder

#include "pspimport.s"

#ifdef F_sceAsfParser_0000
   IMPORT_START   "sceAsfParser",0x00090000
#endif
#ifdef F_sceAsfParser_0001
   IMPORT_FUNC   "sceAsfParser",0x24DB62B1,sceAsfParser_24DB62B1
#endif
#ifdef F_sceAsfParser_0002
   IMPORT_FUNC   "sceAsfParser",0x2CB147F7,sceAsfGetFrameData
#endif
#ifdef F_sceAsfParser_0003
   IMPORT_FUNC   "sceAsfParser",0x320202AB,sceAsfParser_320202AB
#endif
#ifdef F_sceAsfParser_0004
   IMPORT_FUNC   "sceAsfParser",0x3CAAC462,sceAsfReadData
#endif
#ifdef F_sceAsfParser_0005
   IMPORT_FUNC   "sceAsfParser",0x41322F4A,sceAsfParser_41322F4A
#endif
#ifdef F_sceAsfParser_0006
   IMPORT_FUNC   "sceAsfParser",0x685E0DA7,sceAsfParser_685E0DA7
#endif
#ifdef F_sceAsfParser_0007
   IMPORT_FUNC   "sceAsfParser",0x6B3AE857,sceAsfSeekTime
#endif
#ifdef F_sceAsfParser_0008
   IMPORT_FUNC   "sceAsfParser",0x6DA63281,sceAsfParser_6DA63281
#endif
#ifdef F_sceAsfParser_0009
   IMPORT_FUNC   "sceAsfParser",0x91B11F3A,sceAsfInitParser
#endif
#ifdef F_sceAsfParser_0010
   IMPORT_FUNC   "sceAsfParser",0x95AD7B34,sceAsfCheckNeedMem
#endif
#ifdef F_sceAsfParser_0011
   IMPORT_FUNC   "sceAsfParser",0xBC85F4D8,sceAsfParser_BC85F4D8
#endif
#ifdef F_sceAsfParser_0012
   IMPORT_FUNC   "sceAsfParser",0xC6D98C54,sceAsfParser_C6D98C54
#endif
#ifdef F_sceAsfParser_0013
   IMPORT_FUNC   "sceAsfParser",0xF2306E89,sceAsfParser_F2306E89
#endif
