TARGET = envmap
OBJS = envmap.o env0.o

INCDIR =
CFLAGS = -G0 -Wall -O2
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

LIBDIR =
LDFLAGS =
LIBS= -lpspgu

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = Environment Mapping Sample

PSPSDK=$(shell psp-config --pspsdk-path)
USE_PSPSDK_LIBC=1
include $(PSPSDK)/lib/build.mak

env0.o: env0.raw
	bin2o -i env0.raw env0.o env0
